{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.own.owntv",
    "module": "core",
    "version": "1.0.59",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.59.aar",
          "url": "core-1.0.59.aar",
          "size": 7758712,
          "sha512": "37a5996b2649c336d9b99d2b527d3a6b8edbcfd9bc8f89694c8208e63e97e2c7efaaaefaab84375a453445300adeaddea9b36691b99a1095d7b8fc51c0300dbd",
          "sha256": "7a020cce0dbb48476dc974ebdfcf3816aef1682cc22be06e590dca3ca92b3354",
          "sha1": "29e919287595b82bee49c2b008c26743a219acd5",
          "md5": "8bc55c1acd211d906e37d48181760316"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "androidx.tvprovider",
          "module": "tvprovider",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.github.albfernandez",
          "module": "juniversalchardet",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.2.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android"
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.59.aar",
          "url": "core-1.0.59.aar",
          "size": 7758712,
          "sha512": "37a5996b2649c336d9b99d2b527d3a6b8edbcfd9bc8f89694c8208e63e97e2c7efaaaefaab84375a453445300adeaddea9b36691b99a1095d7b8fc51c0300dbd",
          "sha256": "7a020cce0dbb48476dc974ebdfcf3816aef1682cc22be06e590dca3ca92b3354",
          "sha1": "29e919287595b82bee49c2b008c26743a219acd5",
          "md5": "8bc55c1acd211d906e37d48181760316"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.59-sources.jar",
          "url": "core-1.0.59-sources.jar",
          "size": 961889,
          "sha512": "c864204771331d1f292f37d35bf0e241577cedbcdb157867806eef1a445d722eef51a2f4e258834af994bcd0d7ac7f00dd6cf9fc7ebe73ea34d2d141a0caa2e1",
          "sha256": "339551dcb4d650fa5eccf94b39a2a34bd1d5c29f3793038a245a9ae826f7a6f5",
          "sha1": "15f1e3a91226d092c0d23db0aa55ff02809583b7",
          "md5": "e87cd01fa13f9b120a3f4b1516c02584"
        }
      ]
    }
  ]
}
