{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.own.owntv",
    "module": "core",
    "version": "1.0.58",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.58.aar",
          "url": "core-1.0.58.aar",
          "size": 7714283,
          "sha512": "edb47973d70cefbbe011fb5d1ad29d4ccbd6e8d149bacb38f6ff4b60f2eb395fa22785d8129c8f0c2583b68b000f843cbf012f394964755198b28e94621e6752",
          "sha256": "04e5648bb8888af8f35b3891149bdbfa44e21231784dc8437e127d4f1f4f9893",
          "sha1": "95badb1686ab33bfc443a21a5ac433cc045a2dca",
          "md5": "3eab46d300c67ec28a90f20030ddfe8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "androidx.tvprovider",
          "module": "tvprovider",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.github.albfernandez",
          "module": "juniversalchardet",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.2.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android"
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.58.aar",
          "url": "core-1.0.58.aar",
          "size": 7714283,
          "sha512": "edb47973d70cefbbe011fb5d1ad29d4ccbd6e8d149bacb38f6ff4b60f2eb395fa22785d8129c8f0c2583b68b000f843cbf012f394964755198b28e94621e6752",
          "sha256": "04e5648bb8888af8f35b3891149bdbfa44e21231784dc8437e127d4f1f4f9893",
          "sha1": "95badb1686ab33bfc443a21a5ac433cc045a2dca",
          "md5": "3eab46d300c67ec28a90f20030ddfe8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.58-sources.jar",
          "url": "core-1.0.58-sources.jar",
          "size": 955842,
          "sha512": "092eb07d76038e87b10a2b89a222f992ad3f02f5ee6f526b06cece185088dbe0d66f95d1c6a7bd1e7f0f838ec43f710b3d5055b86e2afb4e6a0c6a72b2d4b155",
          "sha256": "a92b724166809a7566057ea9a9a0bf98d521f2ecbef859f2846fcf229a0f4f17",
          "sha1": "fdb9c86431c7da40febc193ddcd2c8c9685ae296",
          "md5": "9bf7d5ce06af0420360eaa30987a5e9b"
        }
      ]
    }
  ]
}
